# -*- coding: utf-8 -*-
{
    'name': "nexus_nms",

    'summary': 'Diwan For Scientific Solution',
    'author': 'Powered By Diwan For Scientific Solution',
    'description': "Powered By Reap Holding - Smart Scientific Solutions",
    'depends': ['base', 'mail', 'openeducat_activity', 'openeducat_erp', 'openeducat_core', 'openeducat_facility',
                'web', 'openeducat_admission', 'openeducat_assignment', 'openeducat_attendance', 'openeducat_parent',
                'openeducat_library', 'openeducat_classroom', 'openeducat_exam', 'project', 'hr_recruitment', 'survey',
                'account'],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'views/masrtech_student_training.xml',
        'views/student_portfolio_template.xml',
        'views/masrtech_factory.xml',
        'views/masrtech_problem.xml',
        'views/week_schedule.xml',
        # 'views/email_qr_code_template.xml',
        'views/masrtech_student_recommendation.xml',
        'views/masrtech_staff_recommendation.xml',
        'views/student_recommendation_register.xml',
        'views/masrtech_project.xml',
        'views/masrtech_job_opportunity.xml',
        'views/masrtech_student_accept.xml',
        'views/masrtech_training.xml',
        'views/masrtech_courses.xml',
        'views/masrtech_training_recommendation.xml',
        'views/inherit_masrtech_student.xml',
        'views/inherit_masrtech_faculties.xml',
        'views/masrtech_universities.xml',
        'views/masrtech_faculty.xml',
        'views/masrtech_industry_type.xml',
        'views/masrtech_registration.xml',
        'views/masrtech_int.xml',
        'views/cocacola.xml',
        'views/masrtech_industries_health.xml',
        'views/masrtech_industries_manufacture.xml',
        'views/template.xml',
        'views/masrtech_key_partner_register.xml',
        'views/inherit_masrtech_configuration.xml',
        'views/inherit_survey.xml',
        'views/masrtech_configuration.xml',
        'views/offer_model.xml',
        'views/certification.xml',
        'views/program_reg.xml',
        'views/dashboard.xml',
        'views/dashboard_doctor.xml',
        'views/inherit_project_task.xml',
        'views/inherit_product_template.xml',
        # 'views/masrtech_student_portfolio.xml',
        # 'views/student_portfolio_views.xml',
        'views/student_search_template.xml',
        'views/student_search_menu.xml',
        'views/payment_way.xml',
        'views/menus.xml',
        'website/home.xml',
        'data/sequence_data.xml',
        'data/cron.xml',
        'website/partner_registration_template.xml',
        'website/student_registration_template.xml',
        'website/consultation_template.xml',
        'website/doctor_registration_template.xml',
        'website/custom-footer-website.xml',
        'website/top-nav.xml',
        'website/program_details.xml',
        'website/apply_template.xml',
        'website/confirmation_apply.xml',
        'website/contact_us_template.xml',
        'website/payment.xml',
        'website/all_courses.xml',
        'website/course_details.xml',
        'website/refund_request_confirm.xml',
        'website/refund_request_template.xml',
        'website/healthCare_analysis.xml',
        'website/hospital_departments_template.xml',
        'website/it_system.xml',
        'website/all_programs.xml',
        'website/confirmation_apply_arabic.xml',
        'website/contact_us_confirmation_arab.xml',
        'website/contact_us_confirmation_en.xml',
        'website/categories.xml',
        'website/registration_for_training.xml',
        'website/training_page.xml',
        'website/course_page.xml',
        'website/program_details_test.xml',
        'website/inherit_navbar.xml',
        'website/template_chatbot.xml',
        'website/invitation-link.xml',
        'website/cocacola_registration.xml',
        'website/handsOnTrainCourse.xml',
        # 'website/tms2.xml',
        'website/blog.xml',
        'website/training_registration_template.xml',
        'website/survey_registration_template.xml',

    ],
    'assets': {
        'web.assets_frontend': [
            '/nexus_nms/static/src/scss/style.scss',
            # '/nexus_nms/static/src/xml/welcome_meeting.xml'
        ],
        'web.assets_backend': [
            '/nexus_nms/static/src/scss/style.scss',
            # '/nexus_nms/static/src/js/validation.js',
            'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css',

        ],
        'web.assets_qweb': [
            '/nexus_nms/view/dashboard_doctor.xml',

        ],
    },

    'version': '0.0.1',
    'application': True,
    'installable': True,

}
